<?php
session_start();

if(!isset($_SESSION["theme"]))
{
    $_SESSION["theme"] = "light";
}
?>
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Text 2</title>
<link rel="shortcut icon" href="/images/minicon.png">
<link rel="stylesheet" href="/styles/text.css">
<link rel="stylesheet" href="/styles/button.css">
<link rel="stylesheet" href="/styles/navigation.css">
<link rel="stylesheet" type="text/css" href="styles/<?php echo $_SESSION["theme"]; ?>.css" id="theme-link">

</head>
<body>

<div class="navigate">
  <img class="menu" src="images/menu_<?php echo $_SESSION["theme"]; ?>.png" onclick="document.location='content.php'"></img>
  <img class="icon" src="images/icon_<?php echo $_SESSION["theme"]; ?>.png" onclick="document.location='index.php'"></img>
</div>

<h1 class="name">FROM ELECTROMECHANICAL TO ELECTRONIC COMPUTERS: AIKEN TO ENIAC</h1>

<div class="text">
<p>For over 30 years, Thomas J. Watson, Sr., one of the supersalesmen of the 20th century, ran International Business Machines Corp. (IBM) with an autocratic hand. As a result, the company that emerged as a successor to Herman Hollerith's Tabulating Machine Company was highly successful at selling mechanicalcalculators to business.

<p>It was only natural, then, that a young Harvard associate professor of mathematics, Howard H. Aiken, after reading Charles Babbage and Ada Byron's notes and conceiving of a modern equivalent of Babbage's analytical engine, should approach Watson for research funds. The cranky head of IBM, after hearing a pitch for the commercial possibilities, thereupon gave Aiken a million dollars. As a result, the Harvard Mark I was born.

<p>Nothing like the Mark I had ever been built before. Eight feet high and 55 feet long, made of streamlined steel and glass, it emitted a sound that one person said was «like listening to a roomful of old ladies knitting away with steel needles.» Whereas Babbage's original machine had been mechanical, the Mark I was electromechanical, using electromagnetic relays (not vacuum tubes) in combination with mechanical counters. Unveiled in 1944, the Mark I had enormous publicity value for IBM, but it was never really efficient. The invention of a truly electronic computer came from other quarters.

<p>Who is the true inventor of the electronic computer? In 1974, a federal court determined, as a result of patent litigation, that Dr. John V. Atanasoff was the originator of the ideas required tо make an electronic digital computer actually work. However, some computer historians dispute this court decision, attributing that designation to Dr. John Mauchly. The background is as follows.

<p>In the late 1930s, Atanasoff, a professor of physics at what is now Iowa State University, spent time trying to build an electronic calculating device to help his students solve complicated mathematical problems. One night, while sitting in an

Illinois roadside tavern, after having driven 189 miles to clear his thoughts, the idea came to him for linking the computer memory and associated logic. With the help of a graduate student, Clifford Berry, and using vacuum tubes, he built the first digital computer that worked electronically. The computer was called the ABC, for «Atanasoff-Berry Computer».

<p>During the years of 1940-41, Atanasoff met with Mauchly, who was then a professor with the Moore School of Electrical Engineering at the University of Pennsylvania. Mauchly had been interested in building his own computer, and there is a good deal of dispute as to how many of Atanasoff and Berry's ideas he might have utilized. In any case, in 1942 Mauchly and his assistant, J. Presper Eckert, were asked by American military officials to build a machine that would rapidly calculate trajectories for artillery and missiles. The machine they proposed, which would cut the time needed to produce trajectories from 15 minutes to 30 seconds, would employ 18,000 vacuum tubes–and all of them would have to operate simultaneously.

<p>This machine, called ENIAC–for Electronic Numerical Integrator and Calculator–was worked on 24 hours a day for 30 months and was finally turned on in February 1946, too late to aid in the war effort. A massive machine that filled an

entire room, it was able to multiply a pair of numbers in about 3 milliseconds, which made it 300 times faster than any other machine.

<p>There were a number of drawbacks to ENIAC – including serious cooling problems because of the heat generated by all the tubes and, more importantly, ridiculously small storage capacity. Worst of all, the system was quite inflexible.

Each time a program was changed, the machine had to be rewired. This last obstacle was overcome by the Hungarian-born mathematical genius Dr. John von Neumann.

<p>The holder of degrees in chemistry and physics, a great storyteller, and a man with total recall, von Neumann was a member of the Institute for Advanced Study in Princeton, New Jersey. One day in 1945, while waiting for a train in Aberdeen, Maryland, a member of the ENIAC development team, Herman Goldstine, ran into von Neumann, who was then involved in the top-secret work of designing atomic weapons. Since both persons had security clearances, they were able to discuss each other's work, and von Neumann began to realize that the difficulties he was having in the time-consuming checking of his advanced equations could be solved by the high speeds of ENIAC. As a result of that chance meeting, von Neumann joined the ENIAC team as a special consultant.

<p>When the Army requested a more powerful computer than ENIAC, von Neumann responded by proposing the EDVAC (for Electronic Discrete Variable Automatic Computer), which would utilize the stored program concept. That is,

instead of people having to rewire the machine to go to a different program, the machine would, in less than a second, «read» instructions from computer storage for switching to a new program. Von Neumann also proposed that the computer used the binary numbering system (the ENIAC worked on the decimal system), to take advantage of the two-state conditions of electronics («on» and «off» to correspond to 1 and 0).

<p>Mauchly and Eckert and others at the Moore School of Engineering set out to build the EDVAC, but the first computer using the stored program concept was actually the EDSAC, built in 1949 at Cambridge University in England. One reason that EDVAC was delayed was that Eckert and Mauchly founded their own company in 1946 to build what would ultimately be called the UNIVAC computer.</p>
</div>
<div class="btns">
<div class="button_prev">
    <button class="blob-btn" onclick="document.location='text1.1.php'">
        previous text
        <span class="blob-btn__inner">
        <span class="blob-btn__blobs">
            <span class="blob-btn__blob"></span>
            <span class="blob-btn__blob"></span>
            <span class="blob-btn__blob"></span>
            <span class="blob-btn__blob"></span>
        </span>
        </span>
    </button>
    <br/>
    </div>

    <div class="button_unit">
    <button class="blob-btn" onclick="document.location='unit1.php'">
        go to unit
        <span class="blob-btn__inner">
        <span class="blob-btn__blobs">
            <span class="blob-btn__blob"></span>
            <span class="blob-btn__blob"></span>
            <span class="blob-btn__blob"></span>
            <span class="blob-btn__blob"></span>
        </span>
        </span>
    </button>
    <br/>
    </div>

    <div class="button_next">
    <button class="blob-btn" onclick="document.location='text1.3.php'">
        next text
        <span class="blob-btn__inner">
        <span class="blob-btn__blobs">
            <span class="blob-btn__blob"></span>
            <span class="blob-btn__blob"></span>
            <span class="blob-btn__blob"></span>
            <span class="blob-btn__blob"></span>
        </span>
        </span>
    </button>
    <br/>
    </div>
</div>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
  <defs>
    <filter id="goo">
      <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10"></feGaussianBlur>
      <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 21 -7" result="goo"></feColorMatrix>
      <feBlend in2="goo" in="SourceGraphic" result="mix"></feBlend>
    </filter>
  </defs>
</svg>
</body>
</html>